spring.application.name=STOCKSAGE

# Oracle Connection Settings
server.port=8081
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=ainzafrany
spring.datasource.password=AinZafrany12
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

zai.api.key=4664cfea6760416a9463c3113e2bf272.iKRgyZwclh6AuURW
zai.api.url=https://open.bigmodel.cn/api/paas/v4/chat/completions