spring.application.name=STOCKSAGE

# Setting Server
server.port=8081

# Oracle Connection Settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=ainzafrany
spring.datasource.password=AinZafrany12
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Z.AI API Settings 
zai.api.key=sk-60a4c558de2a59e92188a084d9846724df1551c77ed7bc43
zai.api.url=https://open.bigmodel.cn/api/paas/v4/chat/completions